### ISSUE TITLE
warning tests for check_cluster_spec aren't working

### ISSUE THREAD

**Issue by philipmulcahy** [Yelp/puppet-monitoring_check#116]
lines 115 through 128:
`
context "payload" do
    context "should be WARNING" do
      it "when no old-enough aggregates" do
        expect(check.send :check_aggregate, :total => 0, :silenced => 0).to(
          eq(["OK", "No servers running the check"]))
      end

      it "when reached warning threshold" do
        check.send(:check_aggregate, :ok => 60, :total => 100, :silenced => 0, :failing => ["somehosti.hostname.com", "anotherhost.example.com"], :stale => []) do |status, message|
          expect(status).to be(1)
          expect(message).to match(/40%/)
        end
      end
    end
`
  
1) The first test's blurb says it wants a warning, but actually specifies OK is needed.

2) The second test passes the predicate in a block to the check_aggregate, but check_aggregate never yields, so the predicate code is never run. If you modify the test to capture the (status, message) and then pass those to the predicate lines, it fails because OK is returned instead of 1 (warn). Although the spec file configures the check using warning=>30, as far as I can see, the subject code ignores the warning parameter, and never issues warnings.

I'm new to ruby - sorry if I've misunderstood!

**Comment by bobtfish** [comment]
These are both broken.

They need to be:

    status, message = check.send(:check_aggregate, :ok => 60, :total => 100, :silenced => 0, :failing => ["somehosti.hostname.com", "anotherhost.example.com"], :stale => [])
     expect(status).to be(1)
     expect(message).to match(/40%/)

this looks like a mistake (and nobody ever noticing as the code was never executed).

**Comment by philipmulcahy** [comment]
"expect(status).to be(1)" will fail, because the subject class doesn't know about warnings": it can only return OK or CRITICAL. The warning threshold passed in by the test config is ignored.
I think that test implementation bugs are not the root problem - It looks as if (perhaps) the subject code is not as capable as the test author intended (with respect to handling/emitting warnings).

To make the two tests pass without surgery on the subject code, the "warnings" tests would not be anything to do with warnings.

**Comment by bobtfish** [comment]
Heh, I'm good with them being eliminated then (or made to test things the code can actually do, if we don't have similar tests for CRITICAL already and you think that adding them would add value).
