### ISSUE TITLE
multi_cluster check reports payload source as $sensu_cluster_name

### ISSUE THREAD

**Issue by philipmulcahy** [Yelp/puppet-monitoring_check#129]
This means that if there are multiple monitored child clusters, only one of them gets to be reported.
Potential fix: for multi_cluster, qualify the source with the child_cluster_name.

**Comment by somic** [comment]
At what point does it become too much complexity to put into check-cluster.rb?

Complexity of having to deal with many clusters is not going away but we could put complexity in check-cluster.rb or we could put it in puppet that creates these checks. If puppet code to support your use case is too verbose, it can be DRYed up. Yes, puppet may not be as flexible as ruby but there are ways.

I am just increasingly concerned that we are solving the problem in suboptimal way.

**Comment by keymone** [comment]
cluster-check can't report on anything that isn't stored within single redis instance. afaik boundary for that is usually $sensu_cluster_name, so i don't really know what possible solution could we have here short of having giant single redis instance for superregion / whole infra?

**Comment by philipmulcahy** [comment]
For my specific problem (clusters in the same sensu region) I think we should be OK if I haven't left any more bugs, but you're right: there are some use cases our current deployment wouldn't be ideal. Are you thinking that the original (now prefix) of source=sensu_cluster_name is redundant? I thought it was propagated out, so allows us to see where the alert came from.

On 4 May 2017 19:01:00 BST, Maksym Melnychok <notifications@github.com> wrote:
>cluster-check can't report on anything that isn't stored within single
>redis instance. afaik boundary for that is usually $sensu_cluster_name,
>so i don't really know what possible solution could we have here short
>of having giant single redis instance for superregion / whole infra?
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Yelp/puppet-monitoring_check/issues/129#issuecomment-299262914

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by philipmulcahy** [comment]
(child)cluster_name now included in the child cluster result rows.
