### ISSUE TITLE
cluster_check cannot assume that it has access to the check settings

### ISSUE THREAD

**Issue by solarkennedy** [Yelp/puppet-monitoring_check#18]
This code will not work on many of the things I want a cluster check on:
https://github.com/Yelp/puppet-monitoring_check/blob/master/files/check-cluster.rb#L141

It works on puppet because our sensu-servers run puppet, but it won't work on things like "apache".

Please make sure this check can run *without* depending on the local check settings configuration.

I think this is the only place where we use this:
https://github.com/Yelp/puppet-monitoring_check/blob/master/files/check-cluster.rb#L44

**Comment by keymone** [comment]
the only bit we need from check config is it's interval, which is now explicitly passed in cluster check params as target_interval.
