### ISSUE TITLE
cluster_check should ignore checks or hosts that have been silenced

### ISSUE THREAD

**Issue by solarkennedy** [Yelp/puppet-monitoring_check#20]
You can implement this as an option, but it should default to true.

Given a list of events back from the aggregate check, something should check the stashes api and weed out anything that has the whole host silenced, or the check itself silenced, and prune it from the list. 

It should_not adjust the percentage though. Example:

host1/check = failed
host2/check = ok
host3/check = failed (silenced host or check)

Should return 1/2, *not* 1/3.

**Comment by keymone** [comment]
there is now option to ignore silenced servers
