### ISSUE TITLE
Build sensu watchdog meta-check

### ISSUE THREAD

**Issue by solarkennedy** [Yelp/puppet-monitoring_check#28]
This ticket is to build the code that will:
* be deployed and run on all sensu servers
* Actually do things only on the sensu master
* Iterate over all watchdog/* stashes
* If the watchdog stash timeout is expired (tbd how to do this. maybe a "watchdog_exipres" field
* Re-send the alert details to sensu masqurading the originating host, rewriting some of the fields
 * status => 2 (crit)
 * output => "Watchdog expired! Last heard from this check $timestamp."
 * tip => "Remove this watchdog timer by removing this stash? (needs more detail)

cc @georgebashi @somic @trumpcard @keymone @lmovsesjan

**Comment by solarkennedy** [comment]
* bla
 *  bla

**Comment by somic** [comment]
This now can be done with server side checks. I think the requirement "actually do things only on the sensu master" can be dropped. I am going to experiment in a branch.

**Comment by somic** [comment]
First cut:
https://github.com/somic/puppet-monitoring_check/blob/watchdog_meta_check/files/watchdog_meta_check.rb

**Comment by somic** [comment]
@solarkennedy - is this issue still relevant now that we have ttl?

**Comment by solarkennedy** [comment]
NOPE! :)
