### ISSUE TITLE
Arbitrary tags in checks

### ISSUE THREAD

**Issue by jaxxstorm** [Yelp/puppet-monitoring_check#71]
Sometimes it would be nice to pass some arbitrary tags to the monitoring_check which can then be used by handlers. An example of this is the JIRA handler, where you might want to add a set of labels to the ticket. Other handlers options such as [opsgenie](https://www.opsgenie.com/docs/web-api/alert-api#addTagsRequest) support searchable tags for incidents, although pagerduty doesn't (they totally should though!)

We can use the sensu_custom param from the ::sensu::check defined type, but in order to enforce good practice I think we should add this param to monitoring_check and then build in that support to the JIRA handler. It should be empty by default, and anything adding can then be used.

Thoughts @solarkennedy @somic @keymone @bobtfish ?

**Comment by solarkennedy** [comment]
Sounds fine. Remember that the JIRA handler automatically makes tags, so if there is a particular tag you think would be useful to automatically generate (role/team/etc), then see if you can make a nice automatic solution.

Also don't forget you can't use the literal tag keyword: https://docs.puppetlabs.com/puppet/latest/reference/lang_tags.html
But you could do an array for `tags` if you want. Just be sure to document what this is.

I agree this feature would be even more useful if more than one handler (more than jira) could interpret the tags.
