### ISSUE TITLE
possible race condition in check-cluster.rb?

### ISSUE THREAD

**Issue by somic** [Yelp/puppet-monitoring_check#74]
I am getting cluster check alerts with "${x} OK out of ${y} total. Failing hosts: ${list_of_failing_hosts}" where length of $list_of_failing_hosts array is not equal to ($y - $x).

**Comment by keymone** [comment]
could be due to silenced hosts?

https://github.com/Yelp/puppet-monitoring_check/blob/master/files/check-cluster.rb#L150:

    eff_total = total - silenced * (config[:silenced] ? 1 : 0)

**Comment by somic** [comment]
Not in my case - looks like no stashes for any of these hosts.

**Comment by jglukasik** [comment]
Could it be stale hosts?  Looking at "${x} OK out of ${y} total. Failing hosts: ${list_of_failing_hosts}":

 ${x} is the active hosts with status of 0, and ${list_of_failing_hosts} is the active hosts with status of 2.

However, ${y} is all the hosts that are not silenced, even if they are not 'active'. To be active, the client needs to have sent a check result with a timestamp more recent than (now - staleness_interval).

I would expect then that ($y - $x) > length($list_of_failing_hosts), is that the case you're seeing?

**Comment by somic** [comment]
Yes, something like this.

I was able to get this from RedisCheckAggregate.summary method:

{:stale=>[], :failing=>[], :total=>142, :ok=>141, :silenced=>0}
CheckCluster OK: Dry run cluster check successfully executed, with output: OK: 141 OK out of 142 total. 99% OK, 95% threshold

Which was caused by one host having result of its check as 3 (UNKNOWN).

**Comment by somic** [comment]
I think this can be closed now.
